/* generated by tools/gen_patch.py: do not edit */
#pragma once
enum { NPATCH = 384, NBASE = 102 };
typedef struct { const char *key; short min, max, def; const char *fmt; } ptab_t;
static const ptab_t PTAB[NPATCH] = {
    {"osc1_freq", 0, 120, 24, "note"},  /* 0 */
    {"osc1_fine", 0, 100, 49, "cents"},  /* 1 */
    {"osc1_shape", 0, 103, 1, "shape"},  /* 2 */
    {"osc1_glide", 0, 127, 0, "int"},  /* 3 */
    {"osc1_key", 0, 1, 1, "onoff"},  /* 4 */
    {"osc2_freq", 0, 120, 24, "note"},  /* 5 */
    {"osc2_fine", 0, 100, 51, "cents"},  /* 6 */
    {"osc2_shape", 0, 103, 1, "shape"},  /* 7 */
    {"osc2_glide", 0, 127, 0, "int"},  /* 8 */
    {"osc2_key", 0, 1, 1, "onoff"},  /* 9 */
    {"sync", 0, 1, 0, "onoff"},  /* 10 */
    {"glide_mode", 0, 3, 0, "opt"},  /* 11 */
    {"slop", 0, 5, 2, "int"},  /* 12 */
    {"osc_mix", 0, 127, 64, "int"},  /* 13 */
    {"noise", 0, 127, 0, "int"},  /* 14 */
    {"lpf_freq", 0, 164, 148, "int"},  /* 15 */
    {"lpf_res", 0, 127, 0, "int"},  /* 16 */
    {"lpf_key", 0, 127, 0, "int"},  /* 17 */
    {"lpf_audmod", 0, 127, 0, "int"},  /* 18 */
    {"poles", 0, 1, 1, "opt"},  /* 19 */
    {"fenv_amt", 0, 254, 127, "bi"},  /* 20 */
    {"fenv_vel", 0, 127, 0, "int"},  /* 21 */
    {"fenv_delay", 0, 127, 0, "int"},  /* 22 */
    {"fenv_a", 0, 127, 0, "int"},  /* 23 */
    {"fenv_d", 0, 127, 0, "int"},  /* 24 */
    {"fenv_s", 0, 127, 0, "int"},  /* 25 */
    {"fenv_r", 0, 127, 0, "int"},  /* 26 */
    {"vca_level", 0, 127, 0, "int"},  /* 27 */
    {"spread", 0, 127, 0, "int"},  /* 28 */
    {"voice_vol", 0, 127, 127, "int"},  /* 29 */
    {"vca_env", 0, 127, 127, "int"},  /* 30 */
    {"vca_vel", 0, 127, 0, "int"},  /* 31 */
    {"aenv_delay", 0, 127, 0, "int"},  /* 32 */
    {"aenv_a", 0, 127, 0, "int"},  /* 33 */
    {"aenv_d", 0, 127, 64, "int"},  /* 34 */
    {"aenv_s", 0, 127, 64, "int"},  /* 35 */
    {"aenv_r", 0, 127, 64, "int"},  /* 36 */
    {"lfo1_freq", 0, 166, 80, "lfof"},  /* 37 */
    {"lfo1_shape", 0, 4, 0, "opt"},  /* 38 */
    {"lfo1_amt", 0, 127, 0, "int"},  /* 39 */
    {"lfo1_dest", 0, 43, 0, "opt"},  /* 40 */
    {"lfo1_sync", 0, 1, 0, "onoff"},  /* 41 */
    {"lfo2_freq", 0, 166, 80, "lfof"},  /* 42 */
    {"lfo2_shape", 0, 4, 0, "opt"},  /* 43 */
    {"lfo2_amt", 0, 127, 0, "int"},  /* 44 */
    {"lfo2_dest", 0, 43, 0, "opt"},  /* 45 */
    {"lfo2_sync", 0, 1, 0, "onoff"},  /* 46 */
    {"lfo3_freq", 0, 166, 80, "lfof"},  /* 47 */
    {"lfo3_shape", 0, 4, 0, "opt"},  /* 48 */
    {"lfo3_amt", 0, 127, 0, "int"},  /* 49 */
    {"lfo3_dest", 0, 43, 0, "opt"},  /* 50 */
    {"lfo3_sync", 0, 1, 0, "onoff"},  /* 51 */
    {"lfo4_freq", 0, 166, 80, "lfof"},  /* 52 */
    {"lfo4_shape", 0, 4, 0, "opt"},  /* 53 */
    {"lfo4_amt", 0, 127, 0, "int"},  /* 54 */
    {"lfo4_dest", 0, 43, 0, "opt"},  /* 55 */
    {"lfo4_sync", 0, 1, 0, "onoff"},  /* 56 */
    {"env3_dest", 0, 43, 0, "opt"},  /* 57 */
    {"env3_amt", 0, 254, 127, "bi"},  /* 58 */
    {"env3_vel", 0, 127, 0, "int"},  /* 59 */
    {"env3_delay", 0, 127, 0, "int"},  /* 60 */
    {"env3_a", 0, 127, 0, "int"},  /* 61 */
    {"env3_d", 0, 127, 0, "int"},  /* 62 */
    {"env3_s", 0, 127, 0, "int"},  /* 63 */
    {"env3_r", 0, 127, 0, "int"},  /* 64 */
    {"mod1_src", 0, 20, 0, "opt"},  /* 65 */
    {"mod1_amt", 0, 254, 127, "bi"},  /* 66 */
    {"mod1_dest", 0, 43, 0, "opt"},  /* 67 */
    {"mod2_src", 0, 20, 0, "opt"},  /* 68 */
    {"mod2_amt", 0, 254, 127, "bi"},  /* 69 */
    {"mod2_dest", 0, 43, 0, "opt"},  /* 70 */
    {"mod3_src", 0, 20, 0, "opt"},  /* 71 */
    {"mod3_amt", 0, 254, 127, "bi"},  /* 72 */
    {"mod3_dest", 0, 43, 0, "opt"},  /* 73 */
    {"mod4_src", 0, 20, 0, "opt"},  /* 74 */
    {"mod4_amt", 0, 254, 127, "bi"},  /* 75 */
    {"mod4_dest", 0, 43, 0, "opt"},  /* 76 */
    {"seq1_dest", 0, 43, 0, "opt"},  /* 77 */
    {"seq2_dest", 0, 43, 0, "opt"},  /* 78 */
    {"seq3_dest", 0, 43, 0, "opt"},  /* 79 */
    {"seq4_dest", 0, 43, 0, "opt"},  /* 80 */
    {"wheel_amt", 0, 254, 127, "bi"},  /* 81 */
    {"wheel_dest", 0, 43, 0, "opt"},  /* 82 */
    {"press_amt", 0, 254, 127, "bi"},  /* 83 */
    {"press_dest", 0, 43, 0, "opt"},  /* 84 */
    {"breath_amt", 0, 254, 127, "bi"},  /* 85 */
    {"breath_dest", 0, 43, 0, "opt"},  /* 86 */
    {"vel_amt", 0, 254, 127, "bi"},  /* 87 */
    {"vel_dest", 0, 43, 0, "opt"},  /* 88 */
    {"foot_amt", 0, 254, 127, "bi"},  /* 89 */
    {"foot_dest", 0, 43, 0, "opt"},  /* 90 */
    {"tempo", 30, 250, 120, "tempo"},  /* 91 */
    {"clock_div", 0, 12, 2, "opt"},  /* 92 */
    {"bend_range", 0, 12, 4, "int"},  /* 93 */
    {"seq_trig", 0, 4, 0, "opt"},  /* 94 */
    {"unison_mode", 0, 4, 2, "opt"},  /* 95 */
    {"key_mode", 0, 5, 0, "opt"},  /* 96 */
    {"arp_mode", 0, 14, 0, "opt"},  /* 97 */
    {"env3_repeat", 0, 1, 0, "onoff"},  /* 98 */
    {"unison", 0, 1, 0, "onoff"},  /* 99 */
    {"arp", 0, 1, 0, "onoff"},  /* 100 */
    {"gseq", 0, 1, 0, "onoff"},  /* 101 */
    {"", 0, 0, 0, "unused"},  /* 102 */
    {"", 0, 0, 0, "unused"},  /* 103 */
    {"", 0, 0, 0, "unused"},  /* 104 */
    {"", 0, 0, 0, "unused"},  /* 105 */
    {"", 0, 0, 0, "unused"},  /* 106 */
    {"", 0, 0, 0, "unused"},  /* 107 */
    {"", 0, 0, 0, "unused"},  /* 108 */
    {"", 0, 0, 0, "unused"},  /* 109 */
    {"", 0, 0, 0, "unused"},  /* 110 */
    {"", 0, 0, 0, "unused"},  /* 111 */
    {"", 0, 0, 0, "unused"},  /* 112 */
    {"", 0, 0, 0, "unused"},  /* 113 */
    {"", 0, 0, 0, "unused"},  /* 114 */
    {"", 0, 0, 0, "unused"},  /* 115 */
    {"", 0, 0, 0, "unused"},  /* 116 */
    {"", 0, 0, 0, "unused"},  /* 117 */
    {"split_point", 0, 127, 60, "note"},  /* 118 */
    {"kbd_mode", 0, 2, 0, "opt"},  /* 119 */
    {"as1_1", 0, 127, 0, "step1"},  /* 120 */
    {"as1_2", 0, 127, 0, "step1"},  /* 121 */
    {"as1_3", 0, 127, 0, "step1"},  /* 122 */
    {"as1_4", 0, 127, 0, "step1"},  /* 123 */
    {"as1_5", 0, 127, 0, "step1"},  /* 124 */
    {"as1_6", 0, 127, 0, "step1"},  /* 125 */
    {"as1_7", 0, 127, 0, "step1"},  /* 126 */
    {"as1_8", 0, 127, 0, "step1"},  /* 127 */
    {"as1_9", 0, 127, 0, "step1"},  /* 128 */
    {"as1_10", 0, 127, 0, "step1"},  /* 129 */
    {"as1_11", 0, 127, 0, "step1"},  /* 130 */
    {"as1_12", 0, 127, 0, "step1"},  /* 131 */
    {"as1_13", 0, 127, 0, "step1"},  /* 132 */
    {"as1_14", 0, 127, 0, "step1"},  /* 133 */
    {"as1_15", 0, 127, 0, "step1"},  /* 134 */
    {"as1_16", 0, 127, 0, "step1"},  /* 135 */
    {"as2_1", 0, 126, 0, "step2"},  /* 136 */
    {"as2_2", 0, 126, 0, "step2"},  /* 137 */
    {"as2_3", 0, 126, 0, "step2"},  /* 138 */
    {"as2_4", 0, 126, 0, "step2"},  /* 139 */
    {"as2_5", 0, 126, 0, "step2"},  /* 140 */
    {"as2_6", 0, 126, 0, "step2"},  /* 141 */
    {"as2_7", 0, 126, 0, "step2"},  /* 142 */
    {"as2_8", 0, 126, 0, "step2"},  /* 143 */
    {"as2_9", 0, 126, 0, "step2"},  /* 144 */
    {"as2_10", 0, 126, 0, "step2"},  /* 145 */
    {"as2_11", 0, 126, 0, "step2"},  /* 146 */
    {"as2_12", 0, 126, 0, "step2"},  /* 147 */
    {"as2_13", 0, 126, 0, "step2"},  /* 148 */
    {"as2_14", 0, 126, 0, "step2"},  /* 149 */
    {"as2_15", 0, 126, 0, "step2"},  /* 150 */
    {"as2_16", 0, 126, 0, "step2"},  /* 151 */
    {"as3_1", 0, 126, 0, "step2"},  /* 152 */
    {"as3_2", 0, 126, 0, "step2"},  /* 153 */
    {"as3_3", 0, 126, 0, "step2"},  /* 154 */
    {"as3_4", 0, 126, 0, "step2"},  /* 155 */
    {"as3_5", 0, 126, 0, "step2"},  /* 156 */
    {"as3_6", 0, 126, 0, "step2"},  /* 157 */
    {"as3_7", 0, 126, 0, "step2"},  /* 158 */
    {"as3_8", 0, 126, 0, "step2"},  /* 159 */
    {"as3_9", 0, 126, 0, "step2"},  /* 160 */
    {"as3_10", 0, 126, 0, "step2"},  /* 161 */
    {"as3_11", 0, 126, 0, "step2"},  /* 162 */
    {"as3_12", 0, 126, 0, "step2"},  /* 163 */
    {"as3_13", 0, 126, 0, "step2"},  /* 164 */
    {"as3_14", 0, 126, 0, "step2"},  /* 165 */
    {"as3_15", 0, 126, 0, "step2"},  /* 166 */
    {"as3_16", 0, 126, 0, "step2"},  /* 167 */
    {"as4_1", 0, 126, 0, "step2"},  /* 168 */
    {"as4_2", 0, 126, 0, "step2"},  /* 169 */
    {"as4_3", 0, 126, 0, "step2"},  /* 170 */
    {"as4_4", 0, 126, 0, "step2"},  /* 171 */
    {"as4_5", 0, 126, 0, "step2"},  /* 172 */
    {"as4_6", 0, 126, 0, "step2"},  /* 173 */
    {"as4_7", 0, 126, 0, "step2"},  /* 174 */
    {"as4_8", 0, 126, 0, "step2"},  /* 175 */
    {"as4_9", 0, 126, 0, "step2"},  /* 176 */
    {"as4_10", 0, 126, 0, "step2"},  /* 177 */
    {"as4_11", 0, 126, 0, "step2"},  /* 178 */
    {"as4_12", 0, 126, 0, "step2"},  /* 179 */
    {"as4_13", 0, 126, 0, "step2"},  /* 180 */
    {"as4_14", 0, 126, 0, "step2"},  /* 181 */
    {"as4_15", 0, 126, 0, "step2"},  /* 182 */
    {"as4_16", 0, 126, 0, "step2"},  /* 183 */
    {"", 0, 0, 0, "unused"},  /* 184 */
    {"", 0, 0, 0, "unused"},  /* 185 */
    {"", 0, 0, 0, "unused"},  /* 186 */
    {"", 0, 0, 0, "unused"},  /* 187 */
    {"", 0, 0, 0, "unused"},  /* 188 */
    {"", 0, 0, 0, "unused"},  /* 189 */
    {"", 0, 0, 0, "unused"},  /* 190 */
    {"", 0, 0, 0, "unused"},  /* 191 */
    {"", 0, 0, 0, "unused"},  /* 192 */
    {"", 0, 0, 0, "unused"},  /* 193 */
    {"", 0, 0, 0, "unused"},  /* 194 */
    {"", 0, 0, 0, "unused"},  /* 195 */
    {"", 0, 0, 0, "unused"},  /* 196 */
    {"", 0, 0, 0, "unused"},  /* 197 */
    {"", 0, 0, 0, "unused"},  /* 198 */
    {"", 0, 0, 0, "unused"},  /* 199 */
    {"b_osc1_freq", 0, 120, 24, "note"},  /* 200 */
    {"b_osc1_fine", 0, 100, 49, "cents"},  /* 201 */
    {"b_osc1_shape", 0, 103, 1, "shape"},  /* 202 */
    {"b_osc1_glide", 0, 127, 0, "int"},  /* 203 */
    {"b_osc1_key", 0, 1, 1, "onoff"},  /* 204 */
    {"b_osc2_freq", 0, 120, 24, "note"},  /* 205 */
    {"b_osc2_fine", 0, 100, 51, "cents"},  /* 206 */
    {"b_osc2_shape", 0, 103, 1, "shape"},  /* 207 */
    {"b_osc2_glide", 0, 127, 0, "int"},  /* 208 */
    {"b_osc2_key", 0, 1, 1, "onoff"},  /* 209 */
    {"b_sync", 0, 1, 0, "onoff"},  /* 210 */
    {"b_glide_mode", 0, 3, 0, "opt"},  /* 211 */
    {"b_slop", 0, 5, 2, "int"},  /* 212 */
    {"b_osc_mix", 0, 127, 64, "int"},  /* 213 */
    {"b_noise", 0, 127, 0, "int"},  /* 214 */
    {"b_lpf_freq", 0, 164, 148, "int"},  /* 215 */
    {"b_lpf_res", 0, 127, 0, "int"},  /* 216 */
    {"b_lpf_key", 0, 127, 0, "int"},  /* 217 */
    {"b_lpf_audmod", 0, 127, 0, "int"},  /* 218 */
    {"b_poles", 0, 1, 1, "opt"},  /* 219 */
    {"b_fenv_amt", 0, 254, 127, "bi"},  /* 220 */
    {"b_fenv_vel", 0, 127, 0, "int"},  /* 221 */
    {"b_fenv_delay", 0, 127, 0, "int"},  /* 222 */
    {"b_fenv_a", 0, 127, 0, "int"},  /* 223 */
    {"b_fenv_d", 0, 127, 0, "int"},  /* 224 */
    {"b_fenv_s", 0, 127, 0, "int"},  /* 225 */
    {"b_fenv_r", 0, 127, 0, "int"},  /* 226 */
    {"b_vca_level", 0, 127, 0, "int"},  /* 227 */
    {"b_spread", 0, 127, 0, "int"},  /* 228 */
    {"b_voice_vol", 0, 127, 127, "int"},  /* 229 */
    {"b_vca_env", 0, 127, 127, "int"},  /* 230 */
    {"b_vca_vel", 0, 127, 0, "int"},  /* 231 */
    {"b_aenv_delay", 0, 127, 0, "int"},  /* 232 */
    {"b_aenv_a", 0, 127, 0, "int"},  /* 233 */
    {"b_aenv_d", 0, 127, 64, "int"},  /* 234 */
    {"b_aenv_s", 0, 127, 64, "int"},  /* 235 */
    {"b_aenv_r", 0, 127, 64, "int"},  /* 236 */
    {"b_lfo1_freq", 0, 166, 80, "lfof"},  /* 237 */
    {"b_lfo1_shape", 0, 4, 0, "opt"},  /* 238 */
    {"b_lfo1_amt", 0, 127, 0, "int"},  /* 239 */
    {"b_lfo1_dest", 0, 43, 0, "opt"},  /* 240 */
    {"b_lfo1_sync", 0, 1, 0, "onoff"},  /* 241 */
    {"b_lfo2_freq", 0, 166, 80, "lfof"},  /* 242 */
    {"b_lfo2_shape", 0, 4, 0, "opt"},  /* 243 */
    {"b_lfo2_amt", 0, 127, 0, "int"},  /* 244 */
    {"b_lfo2_dest", 0, 43, 0, "opt"},  /* 245 */
    {"b_lfo2_sync", 0, 1, 0, "onoff"},  /* 246 */
    {"b_lfo3_freq", 0, 166, 80, "lfof"},  /* 247 */
    {"b_lfo3_shape", 0, 4, 0, "opt"},  /* 248 */
    {"b_lfo3_amt", 0, 127, 0, "int"},  /* 249 */
    {"b_lfo3_dest", 0, 43, 0, "opt"},  /* 250 */
    {"b_lfo3_sync", 0, 1, 0, "onoff"},  /* 251 */
    {"b_lfo4_freq", 0, 166, 80, "lfof"},  /* 252 */
    {"b_lfo4_shape", 0, 4, 0, "opt"},  /* 253 */
    {"b_lfo4_amt", 0, 127, 0, "int"},  /* 254 */
    {"b_lfo4_dest", 0, 43, 0, "opt"},  /* 255 */
    {"b_lfo4_sync", 0, 1, 0, "onoff"},  /* 256 */
    {"b_env3_dest", 0, 43, 0, "opt"},  /* 257 */
    {"b_env3_amt", 0, 254, 127, "bi"},  /* 258 */
    {"b_env3_vel", 0, 127, 0, "int"},  /* 259 */
    {"b_env3_delay", 0, 127, 0, "int"},  /* 260 */
    {"b_env3_a", 0, 127, 0, "int"},  /* 261 */
    {"b_env3_d", 0, 127, 0, "int"},  /* 262 */
    {"b_env3_s", 0, 127, 0, "int"},  /* 263 */
    {"b_env3_r", 0, 127, 0, "int"},  /* 264 */
    {"b_mod1_src", 0, 20, 0, "opt"},  /* 265 */
    {"b_mod1_amt", 0, 254, 127, "bi"},  /* 266 */
    {"b_mod1_dest", 0, 43, 0, "opt"},  /* 267 */
    {"b_mod2_src", 0, 20, 0, "opt"},  /* 268 */
    {"b_mod2_amt", 0, 254, 127, "bi"},  /* 269 */
    {"b_mod2_dest", 0, 43, 0, "opt"},  /* 270 */
    {"b_mod3_src", 0, 20, 0, "opt"},  /* 271 */
    {"b_mod3_amt", 0, 254, 127, "bi"},  /* 272 */
    {"b_mod3_dest", 0, 43, 0, "opt"},  /* 273 */
    {"b_mod4_src", 0, 20, 0, "opt"},  /* 274 */
    {"b_mod4_amt", 0, 254, 127, "bi"},  /* 275 */
    {"b_mod4_dest", 0, 43, 0, "opt"},  /* 276 */
    {"b_seq1_dest", 0, 43, 0, "opt"},  /* 277 */
    {"b_seq2_dest", 0, 43, 0, "opt"},  /* 278 */
    {"b_seq3_dest", 0, 43, 0, "opt"},  /* 279 */
    {"b_seq4_dest", 0, 43, 0, "opt"},  /* 280 */
    {"b_wheel_amt", 0, 254, 127, "bi"},  /* 281 */
    {"b_wheel_dest", 0, 43, 0, "opt"},  /* 282 */
    {"b_press_amt", 0, 254, 127, "bi"},  /* 283 */
    {"b_press_dest", 0, 43, 0, "opt"},  /* 284 */
    {"b_breath_amt", 0, 254, 127, "bi"},  /* 285 */
    {"b_breath_dest", 0, 43, 0, "opt"},  /* 286 */
    {"b_vel_amt", 0, 254, 127, "bi"},  /* 287 */
    {"b_vel_dest", 0, 43, 0, "opt"},  /* 288 */
    {"b_foot_amt", 0, 254, 127, "bi"},  /* 289 */
    {"b_foot_dest", 0, 43, 0, "opt"},  /* 290 */
    {"b_tempo", 30, 250, 120, "tempo"},  /* 291 */
    {"b_clock_div", 0, 12, 2, "opt"},  /* 292 */
    {"b_bend_range", 0, 12, 4, "int"},  /* 293 */
    {"b_seq_trig", 0, 4, 0, "opt"},  /* 294 */
    {"b_unison_mode", 0, 4, 2, "opt"},  /* 295 */
    {"b_key_mode", 0, 5, 0, "opt"},  /* 296 */
    {"b_arp_mode", 0, 14, 0, "opt"},  /* 297 */
    {"b_env3_repeat", 0, 1, 0, "onoff"},  /* 298 */
    {"b_unison", 0, 1, 0, "onoff"},  /* 299 */
    {"b_arp", 0, 1, 0, "onoff"},  /* 300 */
    {"b_gseq", 0, 1, 0, "onoff"},  /* 301 */
    {"", 0, 0, 0, "unused"},  /* 302 */
    {"", 0, 0, 0, "unused"},  /* 303 */
    {"", 0, 0, 0, "unused"},  /* 304 */
    {"", 0, 0, 0, "unused"},  /* 305 */
    {"", 0, 0, 0, "unused"},  /* 306 */
    {"", 0, 0, 0, "unused"},  /* 307 */
    {"", 0, 0, 0, "unused"},  /* 308 */
    {"", 0, 0, 0, "unused"},  /* 309 */
    {"", 0, 0, 0, "unused"},  /* 310 */
    {"", 0, 0, 0, "unused"},  /* 311 */
    {"", 0, 0, 0, "unused"},  /* 312 */
    {"", 0, 0, 0, "unused"},  /* 313 */
    {"", 0, 0, 0, "unused"},  /* 314 */
    {"", 0, 0, 0, "unused"},  /* 315 */
    {"", 0, 0, 0, "unused"},  /* 316 */
    {"", 0, 0, 0, "unused"},  /* 317 */
    {"", 0, 0, 0, "unused"},  /* 318 */
    {"", 0, 0, 0, "unused"},  /* 319 */
    {"bs1_1", 0, 127, 0, "step1"},  /* 320 */
    {"bs1_2", 0, 127, 0, "step1"},  /* 321 */
    {"bs1_3", 0, 127, 0, "step1"},  /* 322 */
    {"bs1_4", 0, 127, 0, "step1"},  /* 323 */
    {"bs1_5", 0, 127, 0, "step1"},  /* 324 */
    {"bs1_6", 0, 127, 0, "step1"},  /* 325 */
    {"bs1_7", 0, 127, 0, "step1"},  /* 326 */
    {"bs1_8", 0, 127, 0, "step1"},  /* 327 */
    {"bs1_9", 0, 127, 0, "step1"},  /* 328 */
    {"bs1_10", 0, 127, 0, "step1"},  /* 329 */
    {"bs1_11", 0, 127, 0, "step1"},  /* 330 */
    {"bs1_12", 0, 127, 0, "step1"},  /* 331 */
    {"bs1_13", 0, 127, 0, "step1"},  /* 332 */
    {"bs1_14", 0, 127, 0, "step1"},  /* 333 */
    {"bs1_15", 0, 127, 0, "step1"},  /* 334 */
    {"bs1_16", 0, 127, 0, "step1"},  /* 335 */
    {"bs2_1", 0, 126, 0, "step2"},  /* 336 */
    {"bs2_2", 0, 126, 0, "step2"},  /* 337 */
    {"bs2_3", 0, 126, 0, "step2"},  /* 338 */
    {"bs2_4", 0, 126, 0, "step2"},  /* 339 */
    {"bs2_5", 0, 126, 0, "step2"},  /* 340 */
    {"bs2_6", 0, 126, 0, "step2"},  /* 341 */
    {"bs2_7", 0, 126, 0, "step2"},  /* 342 */
    {"bs2_8", 0, 126, 0, "step2"},  /* 343 */
    {"bs2_9", 0, 126, 0, "step2"},  /* 344 */
    {"bs2_10", 0, 126, 0, "step2"},  /* 345 */
    {"bs2_11", 0, 126, 0, "step2"},  /* 346 */
    {"bs2_12", 0, 126, 0, "step2"},  /* 347 */
    {"bs2_13", 0, 126, 0, "step2"},  /* 348 */
    {"bs2_14", 0, 126, 0, "step2"},  /* 349 */
    {"bs2_15", 0, 126, 0, "step2"},  /* 350 */
    {"bs2_16", 0, 126, 0, "step2"},  /* 351 */
    {"bs3_1", 0, 126, 0, "step2"},  /* 352 */
    {"bs3_2", 0, 126, 0, "step2"},  /* 353 */
    {"bs3_3", 0, 126, 0, "step2"},  /* 354 */
    {"bs3_4", 0, 126, 0, "step2"},  /* 355 */
    {"bs3_5", 0, 126, 0, "step2"},  /* 356 */
    {"bs3_6", 0, 126, 0, "step2"},  /* 357 */
    {"bs3_7", 0, 126, 0, "step2"},  /* 358 */
    {"bs3_8", 0, 126, 0, "step2"},  /* 359 */
    {"bs3_9", 0, 126, 0, "step2"},  /* 360 */
    {"bs3_10", 0, 126, 0, "step2"},  /* 361 */
    {"bs3_11", 0, 126, 0, "step2"},  /* 362 */
    {"bs3_12", 0, 126, 0, "step2"},  /* 363 */
    {"bs3_13", 0, 126, 0, "step2"},  /* 364 */
    {"bs3_14", 0, 126, 0, "step2"},  /* 365 */
    {"bs3_15", 0, 126, 0, "step2"},  /* 366 */
    {"bs3_16", 0, 126, 0, "step2"},  /* 367 */
    {"bs4_1", 0, 126, 0, "step2"},  /* 368 */
    {"bs4_2", 0, 126, 0, "step2"},  /* 369 */
    {"bs4_3", 0, 126, 0, "step2"},  /* 370 */
    {"bs4_4", 0, 126, 0, "step2"},  /* 371 */
    {"bs4_5", 0, 126, 0, "step2"},  /* 372 */
    {"bs4_6", 0, 126, 0, "step2"},  /* 373 */
    {"bs4_7", 0, 126, 0, "step2"},  /* 374 */
    {"bs4_8", 0, 126, 0, "step2"},  /* 375 */
    {"bs4_9", 0, 126, 0, "step2"},  /* 376 */
    {"bs4_10", 0, 126, 0, "step2"},  /* 377 */
    {"bs4_11", 0, 126, 0, "step2"},  /* 378 */
    {"bs4_12", 0, 126, 0, "step2"},  /* 379 */
    {"bs4_13", 0, 126, 0, "step2"},  /* 380 */
    {"bs4_14", 0, 126, 0, "step2"},  /* 381 */
    {"bs4_15", 0, 126, 0, "step2"},  /* 382 */
    {"bs4_16", 0, 126, 0, "step2"},  /* 383 */
};
static const char *const DEST_NAMES[44] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const SRC_NAMES[21] = {"Off", "Seq 1", "Seq 2", "Seq 3", "Seq 4", "LFO 1", "LFO 2", "LFO 3", "LFO 4", "Filter Env", "Amp Env", "Env 3", "Pitch Bend", "Mod Wheel", "Pressure", "Breath", "Foot", "Expression", "Velocity", "Note Num", "Noise"};
static const char *const OPT_GLIDE_MODE[] = {"Fixed Rate", "Fixed Rate A", "Fixed Time", "Fixed Time A"};
static const char *const OPT_POLES[] = {"2 Pole", "4 Pole"};
static const char *const OPT_LFO1_SHAPE[] = {"Triangle", "Rev Saw", "Sawtooth", "Square", "Random"};
static const char *const OPT_LFO1_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_LFO2_SHAPE[] = {"Triangle", "Rev Saw", "Sawtooth", "Square", "Random"};
static const char *const OPT_LFO2_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_LFO3_SHAPE[] = {"Triangle", "Rev Saw", "Sawtooth", "Square", "Random"};
static const char *const OPT_LFO3_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_LFO4_SHAPE[] = {"Triangle", "Rev Saw", "Sawtooth", "Square", "Random"};
static const char *const OPT_LFO4_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_ENV3_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_MOD1_SRC[] = {"Off", "Seq 1", "Seq 2", "Seq 3", "Seq 4", "LFO 1", "LFO 2", "LFO 3", "LFO 4", "Filter Env", "Amp Env", "Env 3", "Pitch Bend", "Mod Wheel", "Pressure", "Breath", "Foot", "Expression", "Velocity", "Note Num", "Noise"};
static const char *const OPT_MOD1_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_MOD2_SRC[] = {"Off", "Seq 1", "Seq 2", "Seq 3", "Seq 4", "LFO 1", "LFO 2", "LFO 3", "LFO 4", "Filter Env", "Amp Env", "Env 3", "Pitch Bend", "Mod Wheel", "Pressure", "Breath", "Foot", "Expression", "Velocity", "Note Num", "Noise"};
static const char *const OPT_MOD2_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_MOD3_SRC[] = {"Off", "Seq 1", "Seq 2", "Seq 3", "Seq 4", "LFO 1", "LFO 2", "LFO 3", "LFO 4", "Filter Env", "Amp Env", "Env 3", "Pitch Bend", "Mod Wheel", "Pressure", "Breath", "Foot", "Expression", "Velocity", "Note Num", "Noise"};
static const char *const OPT_MOD3_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_MOD4_SRC[] = {"Off", "Seq 1", "Seq 2", "Seq 3", "Seq 4", "LFO 1", "LFO 2", "LFO 3", "LFO 4", "Filter Env", "Amp Env", "Env 3", "Pitch Bend", "Mod Wheel", "Pressure", "Breath", "Foot", "Expression", "Velocity", "Note Num", "Noise"};
static const char *const OPT_MOD4_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_SEQ1_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_SEQ2_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_SEQ3_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_SEQ4_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_WHEEL_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_PRESS_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_BREATH_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_VEL_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_FOOT_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_CLOCK_DIV[] = {"Half", "Quarter", "Eighth", "8 half", "8 swing", "8 trip", "16th", "16 half", "16 swing", "16 trip", "32nd", "32 trip", "64 trip"};
static const char *const OPT_SEQ_TRIG[] = {"Normal", "Normal NoRst", "No Gate", "NoGate NoRst", "Key Step"};
static const char *const OPT_UNISON_MODE[] = {"1 Voice", "All Voices", "Detune 1", "Detune 2", "Detune 3"};
static const char *const OPT_KEY_MODE[] = {"Low", "Low Retrig", "High", "High Retrig", "Last", "Last Retrig"};
static const char *const OPT_ARP_MODE[] = {"Up", "Down", "Up/Down", "Assign", "Random", "2 Oct Up", "2 Oct Down", "2 Oct Up/Down", "2 Oct Assign", "2 Oct Random", "3 Oct Up", "3 Oct Down", "3 Oct Up/Down", "3 Oct Assign", "3 Oct Random"};
static const char *const OPT_KBD_MODE[] = {"Normal", "Stack", "Split"};
static const char *const OPT_B_GLIDE_MODE[] = {"Fixed Rate", "Fixed Rate A", "Fixed Time", "Fixed Time A"};
static const char *const OPT_B_POLES[] = {"2 Pole", "4 Pole"};
static const char *const OPT_B_LFO1_SHAPE[] = {"Triangle", "Rev Saw", "Sawtooth", "Square", "Random"};
static const char *const OPT_B_LFO1_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_B_LFO2_SHAPE[] = {"Triangle", "Rev Saw", "Sawtooth", "Square", "Random"};
static const char *const OPT_B_LFO2_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_B_LFO3_SHAPE[] = {"Triangle", "Rev Saw", "Sawtooth", "Square", "Random"};
static const char *const OPT_B_LFO3_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_B_LFO4_SHAPE[] = {"Triangle", "Rev Saw", "Sawtooth", "Square", "Random"};
static const char *const OPT_B_LFO4_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_B_ENV3_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_B_MOD1_SRC[] = {"Off", "Seq 1", "Seq 2", "Seq 3", "Seq 4", "LFO 1", "LFO 2", "LFO 3", "LFO 4", "Filter Env", "Amp Env", "Env 3", "Pitch Bend", "Mod Wheel", "Pressure", "Breath", "Foot", "Expression", "Velocity", "Note Num", "Noise"};
static const char *const OPT_B_MOD1_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_B_MOD2_SRC[] = {"Off", "Seq 1", "Seq 2", "Seq 3", "Seq 4", "LFO 1", "LFO 2", "LFO 3", "LFO 4", "Filter Env", "Amp Env", "Env 3", "Pitch Bend", "Mod Wheel", "Pressure", "Breath", "Foot", "Expression", "Velocity", "Note Num", "Noise"};
static const char *const OPT_B_MOD2_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_B_MOD3_SRC[] = {"Off", "Seq 1", "Seq 2", "Seq 3", "Seq 4", "LFO 1", "LFO 2", "LFO 3", "LFO 4", "Filter Env", "Amp Env", "Env 3", "Pitch Bend", "Mod Wheel", "Pressure", "Breath", "Foot", "Expression", "Velocity", "Note Num", "Noise"};
static const char *const OPT_B_MOD3_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_B_MOD4_SRC[] = {"Off", "Seq 1", "Seq 2", "Seq 3", "Seq 4", "LFO 1", "LFO 2", "LFO 3", "LFO 4", "Filter Env", "Amp Env", "Env 3", "Pitch Bend", "Mod Wheel", "Pressure", "Breath", "Foot", "Expression", "Velocity", "Note Num", "Noise"};
static const char *const OPT_B_MOD4_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_B_SEQ1_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_B_SEQ2_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_B_SEQ3_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_B_SEQ4_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_B_WHEEL_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_B_PRESS_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_B_BREATH_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_B_VEL_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_B_FOOT_DEST[] = {"Off", "Osc1 Freq", "Osc2 Freq", "Osc1&2 Freq", "Osc Mix", "Noise Level", "Osc1 PW", "Osc2 PW", "Osc1&2 PW", "Filter Freq", "Resonance", "Filter AudMod", "VCA Level", "Pan Spread", "LFO1 Freq", "LFO2 Freq", "LFO3 Freq", "LFO4 Freq", "LFOAll Freq", "LFO1 Amt", "LFO2 Amt", "LFO3 Amt", "LFO4 Amt", "LFOAll Amt", "FltEnv Amt", "AmpEnv Amt", "Env3 Amt", "EnvAll Amt", "Env1 Attack", "Env2 Attack", "Env3 Attack", "EnvAll Attk", "Env1 Decay", "Env2 Decay", "Env3 Decay", "EnvAll Dcy", "Env1 Release", "Env2 Release", "Env3 Release", "EnvAll Rel", "Mod1 Amt", "Mod2 Amt", "Mod3 Amt", "Mod4 Amt"};
static const char *const OPT_B_CLOCK_DIV[] = {"Half", "Quarter", "Eighth", "8 half", "8 swing", "8 trip", "16th", "16 half", "16 swing", "16 trip", "32nd", "32 trip", "64 trip"};
static const char *const OPT_B_SEQ_TRIG[] = {"Normal", "Normal NoRst", "No Gate", "NoGate NoRst", "Key Step"};
static const char *const OPT_B_UNISON_MODE[] = {"1 Voice", "All Voices", "Detune 1", "Detune 2", "Detune 3"};
static const char *const OPT_B_KEY_MODE[] = {"Low", "Low Retrig", "High", "High Retrig", "Last", "Last Retrig"};
static const char *const OPT_B_ARP_MODE[] = {"Up", "Down", "Up/Down", "Assign", "Random", "2 Oct Up", "2 Oct Down", "2 Oct Up/Down", "2 Oct Assign", "2 Oct Random", "3 Oct Up", "3 Oct Down", "3 Oct Up/Down", "3 Oct Assign", "3 Oct Random"};
static const char *const *const POPT[NPATCH] = {
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    OPT_GLIDE_MODE,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    OPT_POLES,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    OPT_LFO1_SHAPE,
    0,
    OPT_LFO1_DEST,
    0,
    0,
    OPT_LFO2_SHAPE,
    0,
    OPT_LFO2_DEST,
    0,
    0,
    OPT_LFO3_SHAPE,
    0,
    OPT_LFO3_DEST,
    0,
    0,
    OPT_LFO4_SHAPE,
    0,
    OPT_LFO4_DEST,
    0,
    OPT_ENV3_DEST,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    OPT_MOD1_SRC,
    0,
    OPT_MOD1_DEST,
    OPT_MOD2_SRC,
    0,
    OPT_MOD2_DEST,
    OPT_MOD3_SRC,
    0,
    OPT_MOD3_DEST,
    OPT_MOD4_SRC,
    0,
    OPT_MOD4_DEST,
    OPT_SEQ1_DEST,
    OPT_SEQ2_DEST,
    OPT_SEQ3_DEST,
    OPT_SEQ4_DEST,
    0,
    OPT_WHEEL_DEST,
    0,
    OPT_PRESS_DEST,
    0,
    OPT_BREATH_DEST,
    0,
    OPT_VEL_DEST,
    0,
    OPT_FOOT_DEST,
    0,
    OPT_CLOCK_DIV,
    0,
    OPT_SEQ_TRIG,
    OPT_UNISON_MODE,
    OPT_KEY_MODE,
    OPT_ARP_MODE,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    OPT_KBD_MODE,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    OPT_B_GLIDE_MODE,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    OPT_B_POLES,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    OPT_B_LFO1_SHAPE,
    0,
    OPT_B_LFO1_DEST,
    0,
    0,
    OPT_B_LFO2_SHAPE,
    0,
    OPT_B_LFO2_DEST,
    0,
    0,
    OPT_B_LFO3_SHAPE,
    0,
    OPT_B_LFO3_DEST,
    0,
    0,
    OPT_B_LFO4_SHAPE,
    0,
    OPT_B_LFO4_DEST,
    0,
    OPT_B_ENV3_DEST,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    OPT_B_MOD1_SRC,
    0,
    OPT_B_MOD1_DEST,
    OPT_B_MOD2_SRC,
    0,
    OPT_B_MOD2_DEST,
    OPT_B_MOD3_SRC,
    0,
    OPT_B_MOD3_DEST,
    OPT_B_MOD4_SRC,
    0,
    OPT_B_MOD4_DEST,
    OPT_B_SEQ1_DEST,
    OPT_B_SEQ2_DEST,
    OPT_B_SEQ3_DEST,
    OPT_B_SEQ4_DEST,
    0,
    OPT_B_WHEEL_DEST,
    0,
    OPT_B_PRESS_DEST,
    0,
    OPT_B_BREATH_DEST,
    0,
    OPT_B_VEL_DEST,
    0,
    OPT_B_FOOT_DEST,
    0,
    OPT_B_CLOCK_DIV,
    0,
    OPT_B_SEQ_TRIG,
    OPT_B_UNISON_MODE,
    OPT_B_KEY_MODE,
    OPT_B_ARP_MODE,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
};
enum {
    P_OSC1_FREQ = 0,
    P_OSC1_FINE = 1,
    P_OSC1_SHAPE = 2,
    P_OSC1_GLIDE = 3,
    P_OSC1_KEY = 4,
    P_OSC2_FREQ = 5,
    P_OSC2_FINE = 6,
    P_OSC2_SHAPE = 7,
    P_OSC2_GLIDE = 8,
    P_OSC2_KEY = 9,
    P_SYNC = 10,
    P_GLIDE_MODE = 11,
    P_SLOP = 12,
    P_OSC_MIX = 13,
    P_NOISE = 14,
    P_LPF_FREQ = 15,
    P_LPF_RES = 16,
    P_LPF_KEY = 17,
    P_LPF_AUDMOD = 18,
    P_POLES = 19,
    P_FENV_AMT = 20,
    P_FENV_VEL = 21,
    P_FENV_DELAY = 22,
    P_FENV_A = 23,
    P_FENV_D = 24,
    P_FENV_S = 25,
    P_FENV_R = 26,
    P_VCA_LEVEL = 27,
    P_SPREAD = 28,
    P_VOICE_VOL = 29,
    P_VCA_ENV = 30,
    P_VCA_VEL = 31,
    P_AENV_DELAY = 32,
    P_AENV_A = 33,
    P_AENV_D = 34,
    P_AENV_S = 35,
    P_AENV_R = 36,
    P_LFO1_FREQ = 37,
    P_LFO1_SHAPE = 38,
    P_LFO1_AMT = 39,
    P_LFO1_DEST = 40,
    P_LFO1_SYNC = 41,
    P_LFO2_FREQ = 42,
    P_LFO2_SHAPE = 43,
    P_LFO2_AMT = 44,
    P_LFO2_DEST = 45,
    P_LFO2_SYNC = 46,
    P_LFO3_FREQ = 47,
    P_LFO3_SHAPE = 48,
    P_LFO3_AMT = 49,
    P_LFO3_DEST = 50,
    P_LFO3_SYNC = 51,
    P_LFO4_FREQ = 52,
    P_LFO4_SHAPE = 53,
    P_LFO4_AMT = 54,
    P_LFO4_DEST = 55,
    P_LFO4_SYNC = 56,
    P_ENV3_DEST = 57,
    P_ENV3_AMT = 58,
    P_ENV3_VEL = 59,
    P_ENV3_DELAY = 60,
    P_ENV3_A = 61,
    P_ENV3_D = 62,
    P_ENV3_S = 63,
    P_ENV3_R = 64,
    P_MOD1_SRC = 65,
    P_MOD1_AMT = 66,
    P_MOD1_DEST = 67,
    P_MOD2_SRC = 68,
    P_MOD2_AMT = 69,
    P_MOD2_DEST = 70,
    P_MOD3_SRC = 71,
    P_MOD3_AMT = 72,
    P_MOD3_DEST = 73,
    P_MOD4_SRC = 74,
    P_MOD4_AMT = 75,
    P_MOD4_DEST = 76,
    P_SEQ1_DEST = 77,
    P_SEQ2_DEST = 78,
    P_SEQ3_DEST = 79,
    P_SEQ4_DEST = 80,
    P_WHEEL_AMT = 81,
    P_WHEEL_DEST = 82,
    P_PRESS_AMT = 83,
    P_PRESS_DEST = 84,
    P_BREATH_AMT = 85,
    P_BREATH_DEST = 86,
    P_VEL_AMT = 87,
    P_VEL_DEST = 88,
    P_FOOT_AMT = 89,
    P_FOOT_DEST = 90,
    P_TEMPO = 91,
    P_CLOCK_DIV = 92,
    P_BEND_RANGE = 93,
    P_SEQ_TRIG = 94,
    P_UNISON_MODE = 95,
    P_KEY_MODE = 96,
    P_ARP_MODE = 97,
    P_ENV3_REPEAT = 98,
    P_UNISON = 99,
    P_ARP = 100,
    P_GSEQ = 101,
    P_SPLIT_POINT = 118, P_KBD_MODE = 119, SEQ_A = 120, SEQ_B = 320, B_OFF = 200, NAME_AT = 184
};
